feat: `TestPlanContext`
equinor/attenuation-app pull request #18
Opened 2024-06-27 14:12 UTC by dansvend

Closes #11

2024-06-27 14:18 UTC, tormodAase commented on screens/HelloWorld.tsx
> +    const { navigate } =useAttenuationAppNavigation()
I think linting has been set up incorrectly by me. Should we create an issue?

2024-06-27 14:21 UTC, dansvend commented on screens/HelloWorld.tsx
> +    const { navigate } =useAttenuationAppNavigation()
Yep! I opened an issue for this: #20

2024-06-28 07:28 UTC, tormodAase requested changes
Looking good!

2024-06-28 07:28 UTC, tormodAase commented on contexts/TestPlanContext.tsx
> +export const useTestPlanContext = () => useContext(TestPlanContext);
Not important, but I generally prefer to name the hooks `useX` instead of `useXContext`. The reason I prefer this, is because I don't think it's necessary to mention the technology used. The technology could always change to something else (like Zustand, redux, etc).

2024-06-28 07:28 UTC, tormodAase commented on screens/TestScreen.tsx
> +            }
To make it more clear what I meant, when looking at the design, 4 of the 9 screens don't have a button at the bottom. So I believe the components themselves should add a button at the bottom if necessary.

We can keep a button here for now, since we haven't developed the underlying screens yet. But in that case we can simplify it
```suggestion
{/*temporary button, will be removed*/}
<Button title="neste side" onPress={navigateNext} />
```

2024-06-28 07:28 UTC, tormodAase commented on screens/TestScreen.tsx
> +            }
It could also be a prop at in the `TestPlanPage` type:
```ts
type TestPlanPage = {
    title: string,
    Component: ReactNode
    /* If undefined, no button should be displayed at the bottom */
    bottomNavigationButton?: {
        title: string
    }
};
```

2024-06-28 07:28 UTC, tormodAase commented on contexts/TestPlanContext.tsx
> +export const useTestPlanContext = () => useContext(TestPlanContext);
Makes it easier to refactor in the future if we were to change the technology

2024-06-28 07:45 UTC, dansvend commented on screens/TestScreen.tsx
> +            }
I agree! I added it as a temporary way to get to the results page 🤠 We will adjust this when we implement the screens 💪

2024-06-28 10:33 UTC, dansvend commented on contexts/TestPlanContext.tsx
> +    }
Navigating to `ResultScreen` now happens in `navigateNext` in `TestPlanContext`, ref [50fda98](https://github.com/equinor/attenuation-app/pull/18/commits/50fda98918cf6e481436bd8d3ca937afc10c1e0c).

2024-06-28 10:36 UTC, dansvend commented on contexts/TestPlanContext.tsx
> +export const useTestPlanContext = () => useContext(TestPlanContext);
Renamed `useTestPlanContext` to `useTestPlan`, ref [8738399](https://github.com/equinor/attenuation-app/pull/18/commits/873839985b1a1c08a1fb9fc2f9cc515d860c4c4d).

2024-06-28 11:09 UTC, tormodAase approved these changes

2024-06-28 11:09 UTC, merged