feat: Result screen
equinor/attenuation-app pull request #57
Opened 2024-07-18 12:35 UTC by dansvend

Closes #47

2024-07-18 14:25 UTC, tormodAase requested changes
Looks good! Made some comments

2024-07-18 14:25 UTC, tormodAase commented on screens/ResultScreen/ResultScreen.tsx
> +  };
These functions has a weird mix of pure and not pure. The arguments are not necessary, since they have access to `isAttenuationApproved` and `decibelDifferenceResult` already. However, to split things up, maybe consider moving these outside of `ResultScreen` and convert them to components (in order to use `useDictionary` inside of them)?

2024-07-18 14:25 UTC, tormodAase commented on screens/ResultScreen/ResultScreen.tsx
> +            <ExitButton />
I know the exit button is in the design, but is it really necessary? We already have a button at the bottom of the screen. The exit button's dialog is also a bit weird when shown from the result screen

2024-07-18 14:25 UTC, tormodAase commented on screens/ResultScreen/ResultScreen.tsx
> +            <ExitButton disabled style={styles.invisible} />
Maybe these invisible components would be less confusing if we created a `Spacer` component?

2024-07-18 14:25 UTC, tormodAase commented on screens/ResultScreen/ResultScreen.tsx
> +import { IconButton } from "@equinor/mad-components/dist/components/Button/IconButton";
`Button.Icon`

2024-07-18 14:25 UTC, tormodAase commented on screens/ResultScreen/ResultScreen.tsx
Looks like errors are not handled properly yet
![image](https://github.com/user-attachments/assets/d0677426-1b9b-411a-8e95-c18c2c6ea630)

2024-07-18 15:02 UTC, dansvend commented on screens/ResultScreen/ResultScreen.tsx
> +            <ExitButton disabled style={styles.invisible} />
A spacer component for this purpose would need to have the exact dimensions as the opposing component for `justify-content: "space-between"` to center the title. Since components have different padding and content width I think it's a more maintainable solution to stick with displaying an invisible component of the same component type. Changes to the component padding for example will affect both the invisible and visible components. Invisible components are rarely used so I think we should keep it as it is.

2024-07-18 15:03 UTC, dansvend commented on screens/ResultScreen/ResultScreen.tsx
> +            <ExitButton />
I agree - I don't think we need it so I will remove it.

2024-07-19 10:47 UTC, dansvend commented on components/Checkbox/Checkbox.tsx
> +import { IconButton } from "@equinor/mad-components/dist/components/Button/IconButton";
Fixed

2024-07-19 10:47 UTC, dansvend commented on constants/attenuation.ts
> +export const MAX_ATTENUATION = 32;
I changed this to 34.

2024-07-19 10:48 UTC, dansvend commented on screens/ResultScreen/HelpButton.tsx
> +import { IconButton } from "@equinor/mad-components/dist/components/Button/IconButton";
Fixed

2024-07-19 10:49 UTC, dansvend commented on screens/TestScreen.tsx
> +    return <Button title="" style={styles.invisible} />;
I agree

2024-07-19 10:50 UTC, dansvend commented on screens/ResultScreen/ResultScreen.tsx
> +  };
This has been separated into `Subtitle` and `Description` components.

2024-07-19 10:51 UTC, dansvend commented on screens/ResultScreen/ResultScreen.tsx
> +            <ExitButton disabled style={styles.invisible} />
Removed since the exit button was removed.

2024-07-19 10:51 UTC, dansvend commented on screens/ResultScreen/ResultScreen.tsx
> +import { IconButton } from "@equinor/mad-components/dist/components/Button/IconButton";
Fixed

2024-07-19 10:53 UTC, dansvend commented on screens/ResultScreen/ResultScreen.tsx
If any error occurs, the bars will be at 0 dB attenuation in addition to displaying a description that something went wrong. Please try again.

2024-07-19 11:02 UTC, Jonas-Omdal submitted a review, later dismissed
🔥

2024-07-23 10:19 UTC, Jonas-Omdal approved these changes

2024-07-24 07:37 UTC, merged